# -*- coding: utf-8 -*-
"""business-it-worskhop-moviescraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H67Sf56f6q4uzIyOwEyTMK3Rjop1PSiQ
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
from supabase import create_client
from datetime import datetime
import os

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

HEADERS = {
    "User-Agent": "Mozilla/5.0",
    "Accept-Language": "en-US,en;q=0.9"
}

def scrape_steam_search(query="action", pages=1):
    results = []

    for page in range(pages):
        url = f"https://store.steampowered.com/search/?term={query}&start={page*50}"
        res = requests.get(url, headers=HEADERS)

        soup = BeautifulSoup(res.text, "html.parser")

        rows = soup.select("a.search_result_row")

        scrape_time = datetime.now().isoformat()

        for row in rows:
            title = row.select_one(".title")
            price = row.select_one(".discount_final_price")
            review = row.select_one(".search_review_summary")
            release = row.select_one(".search_released")

            results.append({
                "title": title.text.strip() if title else None,
                "price_text": price.text.strip() if price else None,
                "review_text": review["data-tooltip-html"].split("<br>")[1].split("of")[0] if review else None,
                "release_date": release.text.strip() if release else None,
                "scraped_at": scrape_time
            })

    return pd.DataFrame(results)


df = scrape_steam_search("grand theft auto", pages=2)

print(df.head())

df.to_csv("steam_games.csv", index=False)

df["price"] = (
    df["price_text"]
      .str.replace("€", "", regex=False) # Remove Euro symbol
      .str.replace("$", "", regex=False) # Remove Dollar symbol
      .str.replace(",", ".", regex=False) # Replace European decimal comma with dot
      .replace("Free", "0.0") # Replace "Free" with "0.0"
      .astype(float)
)

df["review"] = (
    df["review_text"]
      .str.replace("%", "", regex=False) # Remove Euro symbol
      .astype(float)
)

# df["price_text"] = df["price"].fillna("Unknown")
# df["review_text"] = df["review_text"].fillna("Unknown")
# df["review"] = df["review"].fillna("Unknown")
# df["price"] = df["price"].fillna("Unknown")

df = df.dropna()



df = df.rename(columns={
    "price_text": "price_raw",
    "review_text": "review_raw",# original scraped string
    "price": "price_eur",          # clea        # clarify what kind of rating
})


df.to_csv("steam_games.csv", index=False)

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()

rows = []
for _, row in df.iterrows():
    rows.append({
        "title":        str(row.get("title", "")),
        "price_eur":    float(row.get("price_eur", 0)),
        "review":  float(row.get("review", 0)),
        "release_date": str(row.get("release_date", "")),
        "scraped_at":   scrape_time,
    })

result = supabase.table("games").insert(rows).execute()
print(f"✅ Inserted {len(rows)} rows into Supabase")
